# Generated by Django 5.1.5 on 2025-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
